        <footer class="footer">
            <div class="container">
                <p class="textmuted"><strong>DISCLAIMER:</strong> This is a work of fiction, created to only be a satire/unversity project. If you are offended or don&apos;t want your subreddit to be featured on our page please contact us on <a>this</a> email.</p>
            </div>
        </footer>
        <script src="js/jquery.min.js"></script>
        <script src="js/bootstrap.min.js"></script>
    </body>
</html>